# scripts/visualize_blade.py
"""
Visualize 3D blade geometry generated by BladeGeometry.
Usage:
    python visualize_blade.py --save blade.png
    python visualize_blade.py --chord 0.40 0.35 0.28 0.18 --twist 30 22 14 6 --save my_blade.png
"""

import sys
import os
import argparse
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Add parent directory to path so we can import from src/geometry
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src', 'geometry'))
from blade_geometry import BladeGeometry


def plot_blade(blade: BladeGeometry, save_path: str = None):
    """Plot 3D blade sections."""
    fig = plt.figure(figsize=(10, 8))
    ax = fig.add_subplot(111, projection='3d')

    # Draw each section
    for i in range(len(blade.sections)):
        pts = blade.get_section_3d_points(i)
        ax.plot(pts[:, 0], pts[:, 1], pts[:, 2], 'b-', lw=0.8, alpha=0.7)

    # Draw hub and tip circles (optional)
    for r in [blade.hub_radius, blade.R]:
        theta = np.linspace(0, 2*np.pi, 30)
        x_circ = 0.01 * np.cos(theta)   # small offset for visibility
        y_circ = 0.01 * np.sin(theta)
        z_circ = np.full_like(theta, r)
        ax.plot(x_circ, y_circ, z_circ, 'k--', lw=0.5)

    # Rotor axis
    ax.plot([0, 0], [0, 0], [blade.hub_radius, blade.R], 'r-', lw=2, label='Rotor axis')
    ax.scatter([0], [0], [blade.hub_radius], color='red', s=50, label='Hub')
    ax.scatter([0], [0], [blade.R], color='green', s=50, label='Tip')

    ax.set_xlabel('Chordwise (m)')
    ax.set_ylabel('Flapwise (m)')
    ax.set_zlabel('Radial (m)')
    ax.set_title(f'Blade Geometry (R={blade.R:.2f}m, Hub={blade.hub_radius:.2f}m)')
    ax.set_box_aspect((1, 0.5, 2.5))
    ax.legend(loc='best')
    ax.grid(True, alpha=0.3)

    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"✅ Figure saved to {save_path}")
    else:
        plt.show()
    plt.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Visualize wind turbine blade')
    parser.add_argument('--chord', nargs=4, type=float,
                        default=[0.35, 0.30, 0.25, 0.15],
                        help='Chord values at 4 control points (m)')
    parser.add_argument('--twist', nargs=4, type=float,
                        default=[25.0, 20.0, 12.0, 5.0],
                        help='Twist values at 4 control points (deg)')
    parser.add_argument('--save', type=str, default=None,
                        help='Save figure to file (e.g., blade.png)')
    parser.add_argument('--R', type=float, default=5.0,
                        help='Rotor radius (m)')
    parser.add_argument('--hub', type=float, default=0.8,
                        help='Hub radius (m)')
    parser.add_argument('--stations', type=int, default=30,
                        help='Number of radial stations')
    args = parser.parse_args()

    # Build blade
    blade = BladeGeometry(R=args.R, hub_radius=args.hub, num_stations=args.stations)
    design = list(args.chord) + list(args.twist)
    data = blade.build_from_vector(design)

    # Print summary
    print(f"✅ Valid: {data['valid']}")
    for msg in data['messages']:
        print(f"⚠️ {msg}")
    print(f"📏 Avg Chord: {np.mean(blade.chord_grid):.3f} m")
    print(f"🌀 Root Twist: {blade.twist_grid[0]:.2f}°")
    print(f"🌀 Tip Twist:  {blade.twist_grid[-1]:.2f}°")
    print(f"⚖️ Estimated mass: {blade.estimate_mass():.2f} kg")

    # Plot
    plot_blade(blade, save_path=args.save)
    # scripts/visualize_blade.py
"""
Visualize 3D blade geometry generated by BladeGeometry.
Usage:
    python visualize_blade.py --save blade.png
    python visualize_blade.py --chord 0.40 0.35 0.28 0.18 --twist 30 22 14 6 --save my_blade.png
"""

import sys
import os
import argparse
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Add parent directory to path so we can import from src/geometry
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src', 'geometry'))
from blade_geometry import BladeGeometry


def plot_blade(blade: BladeGeometry, save_path: str = None):
    """Plot 3D blade sections."""
    fig = plt.figure(figsize=(12, 10))
    ax = fig.add_subplot(111, projection='3d')

    # Draw each section
    for i in range(len(blade.sections)):
        pts = blade.get_section_3d_points(i)
        ax.plot(pts[:, 0], pts[:, 1], pts[:, 2], 'b-', lw=0.8, alpha=0.6)

    # Draw leading edge (first point of each section)
    le_x = [blade.get_section_3d_points(i)[0, 0] for i in range(len(blade.sections))]
    le_y = [blade.get_section_3d_points(i)[0, 1] for i in range(len(blade.sections))]
    le_z = [blade.get_section_3d_points(i)[0, 2] for i in range(len(blade.sections))]
    ax.plot(le_x, le_y, le_z, 'r-', lw=2.5, label='Leading Edge')

    # Draw trailing edge (last point of each section)
    te_x = [blade.get_section_3d_points(i)[-1, 0] for i in range(len(blade.sections))]
    te_y = [blade.get_section_3d_points(i)[-1, 1] for i in range(len(blade.sections))]
    te_z = [blade.get_section_3d_points(i)[-1, 2] for i in range(len(blade.sections))]
    ax.plot(te_x, te_y, te_z, 'g-', lw=2.5, label='Trailing Edge')

    # Draw hub and tip circles
    for r in [blade.hub_radius, blade.R]:
        theta = np.linspace(0, 2*np.pi, 30)
        x_circ = 0.02 * np.cos(theta)
        y_circ = 0.02 * np.sin(theta)
        z_circ = np.full_like(theta, r)
        ax.plot(x_circ, y_circ, z_circ, 'k--', lw=0.8)

    # Rotor axis
    ax.plot([0, 0], [0, 0], [blade.hub_radius, blade.R], 'k-', lw=1.5, label='Rotor axis')
    ax.scatter([0], [0], [blade.hub_radius], color='red', s=80, label='Hub')
    ax.scatter([0], [0], [blade.R], color='green', s=80, label='Tip')

    ax.set_xlabel('Chordwise (m)', fontsize=10)
    ax.set_ylabel('Flapwise (m)', fontsize=10)
    ax.set_zlabel('Radial (m)', fontsize=10)
    ax.set_title(f'Blade Geometry (R={blade.R:.2f}m, Hub={blade.hub_radius:.2f}m)', fontsize=12)
    ax.set_box_aspect((1, 0.5, 2.5))
    ax.legend(loc='best', fontsize=9)
    ax.grid(True, alpha=0.2)

    # Set view angle for better visualization
    ax.view_init(elev=25, azim=-70)

    if save_path:
        # Ensure directory exists
        os.makedirs(os.path.dirname(save_path), exist_ok=True)
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        print(f"✅ Figure saved to {save_path}")
    else:
        plt.show()
    plt.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Visualize wind turbine blade')
    parser.add_argument('--chord', nargs=4, type=float,
                        default=[0.35, 0.30, 0.25, 0.15],
                        help='Chord values at 4 control points (m)')
    parser.add_argument('--twist', nargs=4, type=float,
                        default=[25.0, 20.0, 12.0, 5.0],
                        help='Twist values at 4 control points (deg)')
    parser.add_argument('--save', type=str, default=None,
                        help='Save figure to file (e.g., outputs/figures/blade.png)')
    parser.add_argument('--R', type=float, default=5.0,
                        help='Rotor radius (m)')
    parser.add_argument('--hub', type=float, default=0.8,
                        help='Hub radius (m)')
    parser.add_argument('--stations', type=int, default=30,
                        help='Number of radial stations')
    args = parser.parse_args()

    # Build blade
    blade = BladeGeometry(R=args.R, hub_radius=args.hub, num_stations=args.stations)
    design = list(args.chord) + list(args.twist)
    data = blade.build_from_vector(design)

    # Print summary
    print(f"✅ Valid: {data['valid']}")
    for msg in data['messages']:
        print(f"⚠️ {msg}")
    print(f"📏 Avg Chord: {np.mean(blade.chord_grid):.3f} m")
    print(f"🌀 Root Twist: {blade.twist_grid[0]:.2f}°")
    print(f"🌀 Tip Twist:  {blade.twist_grid[-1]:.2f}°")
    print(f"⚖️ Estimated mass: {blade.estimate_mass():.2f} kg")

    # Plot
    plot_blade(blade, save_path=args.save)